---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: demo
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops
  namespace: demo
spec:
  type: GitHub
  pathname: https://github.com/open-cluster-management/demo-subscription-gitops.git
  #secretRef:
  #  name: my-github-secret