---
    apiVersion: app.k8s.io/v1beta1
    kind: Application
    metadata:
      name: nginx-blue
      namespace: nginx-blue
    spec:
      selector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - nginx-deployment
      componentKinds:
      - group: app.ibm.com/v1alpha1
        kind: Subscription
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: nginx-green
  namespace: nginx-green
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - nginx-deployment
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription