resources:
- namespace.yaml
#- secret.yaml
- channel.yaml
- placementrule.yaml
- subscription-nginx-ingress-blue.yaml
- subscription-nginx-ingress-green.yaml
- subscription-nginx-blue.yaml
- subscription-nginx-green.yaml
- application.yaml
