apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-virtual-host-ingress
spec:
  rules:
  - host: placement-nginx.apps.aws1-hive.dev06.red-chesterfield.com
    http:
      paths:
      - backend:
          serviceName: placement-nginx-service
          servicePort: 8080
