apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: f5-gslb-pacman
  labels:
    app.kubernetes.io/name: f5-gslb-pacman
spec:
  # Added for f5 demonstration
  host: pacman.www-apps.jnphub01.demo.red-chesterfield.com
  path: "/"
  to:
    kind: Service
    name: pacman